<a href="https://colab.research.google.com/github/7625-k/Aircraft-Validation-Report/blob/main/aircraft.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import warnings

# Ignore all DeprecationWarning messages
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
np.random.seed(42)
n = 5000

rpm = np.random.randint(500, 3000, n)  # Engine rotational speed

noise_v = np.random.normal(0, 0.8, n)
vibration_rms = 1 + 0.002 * rpm + noise_v   # V=1+0.002*RPM+noise
vibration_rms = np.clip(vibration_rms, 0.5, 12)

noise_t = np.random.normal(0, 3, n)
temperature = 40 + 0.005 * rpm + 2 * vibration_rms + noise_t   # T = 40 + 0.005*RPM + 2V + noise
temperature = np.clip(temperature, 40, 120)

noise_a = np.random.normal(0, 4, n)
acoustic_db = 50 + 3 * vibration_rms + noise_a   # A = 50 + 3V + noise
acoustic_db = np.clip(acoustic_db, 50, 110)

risk = np.where(
    (vibration_rms > 6) |
    (temperature > 90) |
    (acoustic_db > 85),
    1, 0
)  # 0=Normal,1=High Risk


data = pd.DataFrame({
    "vibration_rms": vibration_rms,
    "temperature": temperature,
    "rpm": rpm,
    "acoustic_db": acoustic_db,
    "risk": risk
})
print("Aircraft Vibration Sensor Data :")
print(data.head())

Aircraft Vibration Sensor Data :
   vibration_rms  temperature   rpm  acoustic_db  risk
0       4.242117    56.649433  1360    63.911513     0
1       3.677850    56.398421  1794    60.597177     0
2       5.230087    55.321575  1630    67.736925     0
3       5.577866    53.460412  1595    70.819576     0
4       6.208026    66.616834  2138    70.650827     1

In [ ]:
data.to_csv("aircraft_sensor_data.csv", index=False)

Loading dataset

In [ ]:
df_pd = pd.read_csv("aircraft_sensor_data.csv")
print(df_pd.head())

   vibration_rms  temperature   rpm  acoustic_db  risk
0       4.242117    56.649433  1360    63.911513     0
1       3.677850    56.398421  1794    60.597177     0
2       5.230087    55.321575  1630    67.736925     0
3       5.577866    53.460412  1595    70.819576     0
4       6.208026    66.616834  2138    70.650827     1

EDA (Exploratory Data Analysis )

In [ ]:
print(df_pd.shape)

(5000, 5)

In [ ]:
print(df_pd.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   vibration_rms  5000 non-null   float64
 1   temperature    5000 non-null   float64
 2   rpm            5000 non-null   int64
 3   acoustic_db    5000 non-null   float64
 4   risk           5000 non-null   int64
dtypes: float64(3), int64(2)
memory usage: 195.4 KB
None

In [ ]:
print(df_pd.describe())

       vibration_rms  temperature          rpm  acoustic_db         risk
count    5000.000000  5000.000000  5000.000000  5000.000000  5000.000000
mean        4.488956    57.742774  1753.904400    63.581022     0.206000
std         1.666961     7.337813   718.028882     6.324236     0.404471
min         0.500000    40.000000   500.000000    50.000000     0.000000
25%         3.233410    52.131247  1143.750000    59.089124     0.000000
50%         4.481624    57.636295  1752.000000    63.507848     0.000000
75%         5.772187    63.437441  2381.000000    68.002169     0.000000
max         9.222111    78.136382  2997.000000    83.465113     1.000000

In [ ]:
print(df_pd["risk"].value_counts())

risk
0    3970
1    1030
Name: count, dtype: int64

Converting Pandas to Polars

In [ ]:
import polars as pl

df_polars = pl.from_pandas(data)

print(df_polars.head())

shape: (5, 5)
┌───────────────┬─────────────┬──────┬─────────────┬──────┐
│ vibration_rms ┆ temperature ┆ rpm  ┆ acoustic_db ┆ risk │
│ ---           ┆ ---         ┆ ---  ┆ ---         ┆ ---  │
│ f64           ┆ f64         ┆ i64  ┆ f64         ┆ i64  │
╞═══════════════╪═════════════╪══════╪═════════════╪══════╡
│ 4.242117      ┆ 56.649433   ┆ 1360 ┆ 63.911513   ┆ 0    │
│ 3.67785       ┆ 56.398421   ┆ 1794 ┆ 60.597177   ┆ 0    │
│ 5.230087      ┆ 55.321575   ┆ 1630 ┆ 67.736925   ┆ 0    │
│ 5.577866      ┆ 53.460412   ┆ 1595 ┆ 70.819576   ┆ 0    │
│ 6.208026      ┆ 66.616834   ┆ 2138 ┆ 70.650827   ┆ 1    │
└───────────────┴─────────────┴──────┴─────────────┴──────┘

Filtering

In [ ]:
high_risk = df_polars.filter(pl.col("risk") == 1)  # High risk machines
print(high_risk.head())

shape: (5, 5)
┌───────────────┬─────────────┬──────┬─────────────┬──────┐
│ vibration_rms ┆ temperature ┆ rpm  ┆ acoustic_db ┆ risk │
│ ---           ┆ ---         ┆ ---  ┆ ---         ┆ ---  │
│ f64           ┆ f64         ┆ i64  ┆ f64         ┆ i64  │
╞═══════════════╪═════════════╪══════╪═════════════╪══════╡
│ 6.208026      ┆ 66.616834   ┆ 2138 ┆ 70.650827   ┆ 1    │
│ 7.498119      ┆ 69.383168   ┆ 2635 ┆ 74.533861   ┆ 1    │
│ 6.885886      ┆ 64.578521   ┆ 2933 ┆ 72.928031   ┆ 1    │
│ 8.860784      ┆ 74.086155   ┆ 2824 ┆ 77.047158   ┆ 1    │
│ 7.100765      ┆ 65.21755    ┆ 2568 ┆ 75.323599   ┆ 1    │
└───────────────┴─────────────┴──────┴─────────────┴──────┘

In [ ]:
high_rpm = df_polars.filter(pl.col("rpm") > 2500)  # Machines with high RPM
print(high_rpm.head())

shape: (5, 5)
┌───────────────┬─────────────┬──────┬─────────────┬──────┐
│ vibration_rms ┆ temperature ┆ rpm  ┆ acoustic_db ┆ risk │
│ ---           ┆ ---         ┆ ---  ┆ ---         ┆ ---  │
│ f64           ┆ f64         ┆ i64  ┆ f64         ┆ i64  │
╞═══════════════╪═════════════╪══════╪═════════════╪══════╡
│ 5.341525      ┆ 62.387697   ┆ 2669 ┆ 63.108512   ┆ 0    │
│ 7.498119      ┆ 69.383168   ┆ 2635 ┆ 74.533861   ┆ 1    │
│ 5.743992      ┆ 65.887916   ┆ 2891 ┆ 60.81613    ┆ 0    │
│ 6.885886      ┆ 64.578521   ┆ 2933 ┆ 72.928031   ┆ 1    │
│ 8.860784      ┆ 74.086155   ┆ 2824 ┆ 77.047158   ┆ 1    │
└───────────────┴─────────────┴──────┴─────────────┴──────┘

In [ ]:
high_vrms = df_polars.filter(pl.col("vibration_rms") > 6) # High vibration machines
print(high_vrms.head())

shape: (5, 5)
┌───────────────┬─────────────┬──────┬─────────────┬──────┐
│ vibration_rms ┆ temperature ┆ rpm  ┆ acoustic_db ┆ risk │
│ ---           ┆ ---         ┆ ---  ┆ ---         ┆ ---  │
│ f64           ┆ f64         ┆ i64  ┆ f64         ┆ i64  │
╞═══════════════╪═════════════╪══════╪═════════════╪══════╡
│ 6.208026      ┆ 66.616834   ┆ 2138 ┆ 70.650827   ┆ 1    │
│ 7.498119      ┆ 69.383168   ┆ 2635 ┆ 74.533861   ┆ 1    │
│ 6.885886      ┆ 64.578521   ┆ 2933 ┆ 72.928031   ┆ 1    │
│ 8.860784      ┆ 74.086155   ┆ 2824 ┆ 77.047158   ┆ 1    │
│ 7.100765      ┆ 65.21755    ┆ 2568 ┆ 75.323599   ┆ 1    │
└───────────────┴─────────────┴──────┴─────────────┴──────┘

In [ ]:
high_acoustic_db = df_polars.filter(pl.col("acoustic_db") > 85) # High acoustic machines i.e is noisy machines
print(high_acoustic_db.head())

shape: (0, 5)
┌───────────────┬─────────────┬─────┬─────────────┬──────┐
│ vibration_rms ┆ temperature ┆ rpm ┆ acoustic_db ┆ risk │
│ ---           ┆ ---         ┆ --- ┆ ---         ┆ ---  │
│ f64           ┆ f64         ┆ i64 ┆ f64         ┆ i64  │
╞═══════════════╪═════════════╪═════╪═════════════╪══════╡
└───────────────┴─────────────┴─────┴─────────────┴──────┘

In [ ]:
high_rpmAndvibration = df_polars.filter(                #  High RPM + High Vibration
    (pl.col("rpm") > 2000) &
    (pl.col("vibration_rms") > 5)
)
print(high_rpmAndvibration.head())

shape: (5, 5)
┌───────────────┬─────────────┬──────┬─────────────┬──────┐
│ vibration_rms ┆ temperature ┆ rpm  ┆ acoustic_db ┆ risk │
│ ---           ┆ ---         ┆ ---  ┆ ---         ┆ ---  │
│ f64           ┆ f64         ┆ i64  ┆ f64         ┆ i64  │
╞═══════════════╪═════════════╪══════╪═════════════╪══════╡
│ 6.208026      ┆ 66.616834   ┆ 2138 ┆ 70.650827   ┆ 1    │
│ 5.341525      ┆ 62.387697   ┆ 2669 ┆ 63.108512   ┆ 0    │
│ 7.498119      ┆ 69.383168   ┆ 2635 ┆ 74.533861   ┆ 1    │
│ 5.067956      ┆ 55.806404   ┆ 2185 ┆ 61.598812   ┆ 0    │
│ 5.743992      ┆ 65.887916   ┆ 2891 ┆ 60.81613    ┆ 0    │
└───────────────┴─────────────┴──────┴─────────────┴──────┘

Aggregation

In [ ]:
agg_pl = df_polars.group_by("risk").mean()
print(agg_pl)

shape: (2, 5)
┌──────┬───────────────┬─────────────┬─────────────┬─────────────┐
│ risk ┆ vibration_rms ┆ temperature ┆ rpm         ┆ acoustic_db │
│ ---  ┆ ---           ┆ ---         ┆ ---         ┆ ---         │
│ i64  ┆ f64           ┆ f64         ┆ f64         ┆ f64         │
╞══════╪═══════════════╪═════════════╪═════════════╪═════════════╡
│ 1    ┆ 6.797133      ┆ 66.66238    ┆ 2612.36699  ┆ 70.498146   │
│ 0    ┆ 3.890109      ┆ 55.428619   ┆ 1531.179849 ┆ 61.786402   │
└──────┴───────────────┴─────────────┴─────────────┴─────────────┘

In [ ]:
df_polars.group_by("risk").count()

shape: (2, 2)
┌──────┬───────┐
│ risk ┆ count │
│ ---  ┆ ---   │
│ i64  ┆ u32   │
╞══════╪═══════╡
│ 0    ┆ 3970  │
│ 1    ┆ 1030  │
└──────┴───────┘

In [ ]:
df_polars.select([
    pl.col("rpm").min().alias("min_rpm"),
    pl.col("rpm").max().alias("max_rpm"),
    pl.col("temperature").max().alias("max_temperature"),
    pl.col("vibration_rms").max().alias("max_vibration")
])

shape: (1, 4)
┌─────────┬─────────┬─────────────────┬───────────────┐
│ min_rpm ┆ max_rpm ┆ max_temperature ┆ max_vibration │
│ ---     ┆ ---     ┆ ---             ┆ ---           │
│ i64     ┆ i64     ┆ f64             ┆ f64           │
╞═════════╪═════════╪═════════════════╪═══════════════╡
│ 500     ┆ 2997    ┆ 78.136382       ┆ 9.222111      │
└─────────┴─────────┴─────────────────┴───────────────┘

# Data Validation (Great Expectations)

In [ ]:
!pip install great_expectations==0.17.23

Requirement already satisfied: great_expectations==0.17.23 in /usr/local/lib/python3.12/dist-packages (0.17.23)
Requirement already satisfied: altair<5.0.0,>=4.2.1 in /usr/local/lib/python3.12/dist-packages (from great_expectations==0.17.23) (4.2.2)
Requirement already satisfied: Click!=8.1.4,>=7.1.2 in /usr/local/lib/python3.12/dist-packages (from great_expectations==0.17.23) (8.3.1)
Requirement already satisfied: colorama>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from great_expectations==0.17.23) (0.4.6)
Requirement already satisfied: cryptography>=3.2 in /usr/local/lib/python3.12/dist-packages (from great_expectations==0.17.23) (43.0.3)
Requirement already satisfied: Ipython>=7.16.3 in /usr/local/lib/python3.12/dist-packages (from great_expectations==0.17.23) (7.34.0)
Requirement already satisfied: ipywidgets>=7.5.1 in /usr/local/lib/python3.12/dist-packages (from great_expectations==0.17.23) (7.7.1)
Requirement already satisfied: jinja2>=2.10 in /usr/local/lib/python3.12/dist-packages (from great_expectations==0.17.23) (3.1.6)
Requirement already satisfied: jsonpatch>=1.22 in /usr/local/lib/python3.12/dist-packages (from great_expectations==0.17.23) (1.33)
Requirement already satisfied: jsonschema>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from great_expectations==0.17.23) (4.26.0)
Requirement already satisfied: makefun<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from great_expectations==0.17.23) (1.16.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.7.1 in /usr/local/lib/python3.12/dist-packages (from great_expectations==0.17.23) (3.26.2)
Requirement already satisfied: mistune>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from great_expectations==0.17.23) (3.2.0)
Requirement already satisfied: nbformat>=5.0 in /usr/local/lib/python3.12/dist-packages (from great_expectations==0.17.23) (5.10.4)
Requirement already satisfied: notebook>=6.4.10 in /usr/local/lib/python3.12/dist-packages (from great_expectations==0.17.23) (6.5.7)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from great_expectations==0.17.23) (26.0)
Requirement already satisfied: pydantic>=1.9.2 in /usr/local/lib/python3.12/dist-packages (from great_expectations==0.17.23) (2.12.3)
Requirement already satisfied: pyparsing>=2.4 in /usr/local/lib/python3.12/dist-packages (from great_expectations==0.17.23) (3.3.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.12/dist-packages (from great_expectations==0.17.23) (2.9.0.post0)
Requirement already satisfied: pytz>=2021.3 in /usr/local/lib/python3.12/dist-packages (from great_expectations==0.17.23) (2025.2)
Requirement already satisfied: requests>=2.20 in /usr/local/lib/python3.12/dist-packages (from great_expectations==0.17.23) (2.32.4)
Requirement already satisfied: ruamel.yaml<0.17.18,>=0.16 in /usr/local/lib/python3.12/dist-packages (from great_expectations==0.17.23) (0.17.17)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from great_expectations==0.17.23) (1.16.3)
Requirement already satisfied: tqdm>=4.59.0 in /usr/local/lib/python3.12/dist-packages (from great_expectations==0.17.23) (4.67.3)
Requirement already satisfied: typing-extensions>=3.10.0.0 in /usr/local/lib/python3.12/dist-packages (from great_expectations==0.17.23) (4.15.0)
Requirement already satisfied: tzlocal>=1.2 in /usr/local/lib/python3.12/dist-packages (from great_expectations==0.17.23) (5.3.1)
Requirement already satisfied: urllib3>=1.26 in /usr/local/lib/python3.12/dist-packages (from great_expectations==0.17.23) (2.5.0)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.12/dist-packages (from great_expectations==0.17.23) (2.0.2)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from great_expectations==0.17.23) (2.2.2)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from altair<5.0.0,>=4.2.1->great_expectations==0.17.23) (0.4)
Requirement already satisfied: toolz in /usr/local/lib/python3.12/dist-packages (from altair<5.0.0,>=4.2.1->great_expectations==0.17.23) (0.12.1)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=3.2->great_expectations==0.17.23) (2.0.0)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from Ipython>=7.16.3->great_expectations==0.17.23) (75.2.0)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.12/dist-packages (from Ipython>=7.16.3->great_expectations==0.17.23) (0.19.2)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from Ipython>=7.16.3->great_expectations==0.17.23) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from Ipython>=7.16.3->great_expectations==0.17.23) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.12/dist-packages (from Ipython>=7.16.3->great_expectations==0.17.23) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from Ipython>=7.16.3->great_expectations==0.17.23) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from Ipython>=7.16.3->great_expectations==0.17.23) (2.19.2)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from Ipython>=7.16.3->great_expectations==0.17.23) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.12/dist-packages (from Ipython>=7.16.3->great_expectations==0.17.23) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from Ipython>=7.16.3->great_expectations==0.17.23) (4.9.0)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=7.5.1->great_expectations==0.17.23) (6.17.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=7.5.1->great_expectations==0.17.23) (0.2.0)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=7.5.1->great_expectations==0.17.23) (3.6.10)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=7.5.1->great_expectations==0.17.23) (3.0.16)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.10->great_expectations==0.17.23) (3.0.3)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch>=1.22->great_expectations==0.17.23) (3.0.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.5.1->great_expectations==0.17.23) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.5.1->great_expectations==0.17.23) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.5.1->great_expectations==0.17.23) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.5.1->great_expectations==0.17.23) (0.30.0)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat>=5.0->great_expectations==0.17.23) (2.21.2)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat>=5.0->great_expectations==0.17.23) (5.9.1)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.4.10->great_expectations==0.17.23) (6.5.1)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.4.10->great_expectations==0.17.23) (26.2.1)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.12/dist-packages (from notebook>=6.4.10->great_expectations==0.17.23) (25.1.0)
Requirement already satisfied: jupyter-client<8,>=5.3.4 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.4.10->great_expectations==0.17.23) (7.4.9)
Requirement already satisfied: nbconvert>=5 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.4.10->great_expectations==0.17.23) (7.17.0)
Requirement already satisfied: nest-asyncio>=1.5 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.4.10->great_expectations==0.17.23) (1.6.0)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.4.10->great_expectations==0.17.23) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.4.10->great_expectations==0.17.23) (0.18.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.12/dist-packages (from notebook>=6.4.10->great_expectations==0.17.23) (0.24.1)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.4.10->great_expectations==0.17.23) (1.3.3)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->great_expectations==0.17.23) (2025.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.9.2->great_expectations==0.17.23) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.9.2->great_expectations==0.17.23) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.9.2->great_expectations==0.17.23) (0.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.1->great_expectations==0.17.23) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->great_expectations==0.17.23) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->great_expectations==0.17.23) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->great_expectations==0.17.23) (2026.1.4)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=3.2->great_expectations==0.17.23) (3.0)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets>=7.5.1->great_expectations==0.17.23) (1.8.15)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets>=7.5.1->great_expectations==0.17.23) (5.9.5)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->Ipython>=7.16.3->great_expectations==0.17.23) (0.8.6)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat>=5.0->great_expectations==0.17.23) (4.6.0)
Requirement already satisfied: notebook-shim>=0.2.3 in /usr/local/lib/python3.12/dist-packages (from nbclassic>=0.4.7->notebook>=6.4.10->great_expectations==0.17.23) (0.2.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=6.4.10->great_expectations==0.17.23) (4.13.5)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=6.4.10->great_expectations==0.17.23) (6.3.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=6.4.10->great_expectations==0.17.23) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=6.4.10->great_expectations==0.17.23) (0.3.0)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=6.4.10->great_expectations==0.17.23) (0.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=6.4.10->great_expectations==0.17.23) (1.5.1)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->Ipython>=7.16.3->great_expectations==0.17.23) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->Ipython>=7.16.3->great_expectations==0.17.23) (0.6.0)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.12/dist-packages (from argon2-cffi->notebook>=6.4.10->great_expectations==0.17.23) (25.1.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=5->notebook>=6.4.10->great_expectations==0.17.23) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=6.4.10->great_expectations==0.17.23) (1.4.0)
Requirement already satisfied: jupyter-server<3,>=1.8 in /usr/local/lib/python3.12/dist-packages (from notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great_expectations==0.17.23) (2.14.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->nbconvert>=5->notebook>=6.4.10->great_expectations==0.17.23) (2.8.3)
Requirement already satisfied: anyio>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great_expectations==0.17.23) (4.12.1)
Requirement already satisfied: jupyter-events>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great_expectations==0.17.23) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great_expectations==0.17.23) (0.5.4)
Requirement already satisfied: overrides>=5.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great_expectations==0.17.23) (7.7.0)
Requirement already satisfied: websocket-client>=1.7 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great_expectations==0.17.23) (1.9.0)
Requirement already satisfied: python-json-logger>=2.0.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great_expectations==0.17.23) (4.0.0)
Requirement already satisfied: pyyaml>=5.3 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great_expectations==0.17.23) (6.0.3)
Requirement already satisfied: rfc3339-validator in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great_expectations==0.17.23) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great_expectations==0.17.23) (0.1.1)
Requirement already satisfied: fqdn in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great_expectations==0.17.23) (1.5.1)
Requirement already satisfied: isoduration in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great_expectations==0.17.23) (20.11.0)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great_expectations==0.17.23) (1.1.0)
Requirement already satisfied: uri-template in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great_expectations==0.17.23) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great_expectations==0.17.23) (25.10.0)
Requirement already satisfied: lark>=1.2.2 in /usr/local/lib/python3.12/dist-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great_expectations==0.17.23) (1.3.1)
Requirement already satisfied: arrow>=0.15.0 in /usr/local/lib/python3.12/dist-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great_expectations==0.17.23) (1.4.0)

In [ ]:
import great_expectations as gx

In [ ]:
!great_expectations init

  ___              _     ___                  _        _   _
 / __|_ _ ___ __ _| |_  | __|_ ___ __  ___ __| |_ __ _| |_(_)___ _ _  ___
| (_ | '_/ -_) _` |  _| | _|\ \ / '_ \/ -_) _|  _/ _` |  _| / _ \ ' \(_-<
 \___|_| \___\__,_|\__| |___/_\_\ .__/\___\__|\__\__,_|\__|_\___/_||_/__/
                                |_|
             ~ Always know what to expect from your data ~

This looks like an existing project that appears complete! You are ready to roll.

In [ ]:
context = gx.get_context()

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/great_expectations/data_context/store/_store_backend.py:90: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parsed_store_backend_id = store_backend_id_file_parser.parseString(

In [ ]:
suite = context.add_or_update_expectation_suite(
    expectation_suite_name="aircraft_suite"
)

In [ ]:
context.sources.add_or_update_pandas(
    name="pandas_datasource"
)

PandasDatasource(type='pandas', name='pandas_datasource', id=None, assets=[])

In [ ]:
datasource = context.get_datasource("pandas_datasource")

In [ ]:
data_asset = datasource.add_dataframe_asset(
    name="aircraft_data"
)

In [ ]:
batch_request = data_asset.build_batch_request(
    dataframe=df_pd
)

In [ ]:
validator = context.get_validator(
    batch_request=batch_request,
    expectation_suite_name="aircraft_suite"
)

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
validator.expect_table_row_count_to_be_between(
    min_value=4000,
    max_value=6000
)

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/great_expectations/expectations/expectation.py:1481: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

{
  "success": true,
  "expectation_config": {
    "expectation_type": "expect_table_row_count_to_be_between",
    "kwargs": {
      "min_value": 4000,
      "max_value": 6000,
      "batch_id": "pandas_datasource-aircraft_data"
    },
    "meta": {}
  },
  "result": {
    "observed_value": 5000
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [ ]:
validator.expect_column_values_to_not_be_null("rpm")

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

{
  "success": true,
  "expectation_config": {
    "expectation_type": "expect_column_values_to_not_be_null",
    "kwargs": {
      "column": "rpm",
      "batch_id": "pandas_datasource-aircraft_data"
    },
    "meta": {}
  },
  "result": {
    "element_count": 5000,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": []
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [ ]:
validator.expect_column_values_to_be_between(
    "temperature",
    min_value=40,
    max_value=120
)

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/great_expectations/expectations/expectation.py:1481: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

{
  "success": true,
  "expectation_config": {
    "expectation_type": "expect_column_values_to_be_between",
    "kwargs": {
      "min_value": 40,
      "max_value": 120,
      "column": "temperature",
      "batch_id": "pandas_datasource-aircraft_data"
    },
    "meta": {}
  },
  "result": {
    "element_count": 5000,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [ ]:
validator.expect_column_values_to_be_between(
    "rpm",
    min_value=500,
    max_value=3000
)

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/great_expectations/expectations/expectation.py:1481: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

{
  "success": true,
  "expectation_config": {
    "expectation_type": "expect_column_values_to_be_between",
    "kwargs": {
      "min_value": 500,
      "max_value": 3000,
      "column": "rpm",
      "batch_id": "pandas_datasource-aircraft_data"
    },
    "meta": {}
  },
  "result": {
    "element_count": 5000,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [ ]:
validator.expect_column_values_to_be_in_set(
    "risk",
    value_set=[0, 1]
)

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/great_expectations/expectations/expectation.py:1481: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

{
  "success": true,
  "expectation_config": {
    "expectation_type": "expect_column_values_to_be_in_set",
    "kwargs": {
      "value_set": [
        0,
        1
      ],
      "column": "risk",
      "batch_id": "pandas_datasource-aircraft_data"
    },
    "meta": {}
  },
  "result": {
    "element_count": 5000,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [ ]:
validator.save_expectation_suite()

In [ ]:
checkpoint = context.add_or_update_checkpoint(
    name="aircraft_checkpoint",
    validator=validator
)

In [ ]:
checkpoint_result = checkpoint.run()

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

Calculating Metrics:   0%|          | 0/27 [00:00<?, ?it/s]

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
context.build_data_docs()

{'local_site': 'file:///content/gx/uncommitted/data_docs/local_site/index.html'}

In [ ]:
context.open_data_docs()

In [ ]:
docs_sites = context.get_docs_sites_urls()

print(docs_sites)

[{'site_name': 'local_site', 'site_url': 'file:///content/gx/uncommitted/data_docs/local_site/index.html'}]

In [ ]:
!zip -r aircraft_validation_report.zip gx/uncommitted/data_docs/

updating: gx/uncommitted/data_docs/ (stored 0%)
updating: gx/uncommitted/data_docs/local_site/ (stored 0%)
updating: gx/uncommitted/data_docs/local_site/index.html (deflated 79%)
updating: gx/uncommitted/data_docs/local_site/expectations/ (stored 0%)
updating: gx/uncommitted/data_docs/local_site/expectations/aircraft_suite.html (deflated 80%)
updating: gx/uncommitted/data_docs/local_site/validations/ (stored 0%)
updating: gx/uncommitted/data_docs/local_site/validations/aircraft_suite/ (stored 0%)
updating: gx/uncommitted/data_docs/local_site/validations/aircraft_suite/__none__/ (stored 0%)
updating: gx/uncommitted/data_docs/local_site/validations/aircraft_suite/__none__/20260218T150644.533916Z/ (stored 0%)
updating: gx/uncommitted/data_docs/local_site/validations/aircraft_suite/__none__/20260218T150644.533916Z/pandas_datasource-aircraft_data.html (deflated 82%)
updating: gx/uncommitted/data_docs/local_site/static/ (stored 0%)
updating: gx/uncommitted/data_docs/local_site/static/images/ (stored 0%)
updating: gx/uncommitted/data_docs/local_site/static/images/iterative-dev-loop.png (stored 0%)
updating: gx/uncommitted/data_docs/local_site/static/images/validation_failed_unexpected_values.gif (deflated 3%)
updating: gx/uncommitted/data_docs/local_site/static/images/logo-long-vector.svg (deflated 66%)
updating: gx/uncommitted/data_docs/local_site/static/images/glossary_scroller.gif (deflated 1%)
updating: gx/uncommitted/data_docs/local_site/static/images/favicon.ico (stored 0%)
updating: gx/uncommitted/data_docs/local_site/static/images/logo-long.png (deflated 1%)
updating: gx/uncommitted/data_docs/local_site/static/images/short-logo-vector.svg (deflated 66%)
updating: gx/uncommitted/data_docs/local_site/static/images/short-logo.png (stored 0%)
updating: gx/uncommitted/data_docs/local_site/static/fonts/ (stored 0%)
updating: gx/uncommitted/data_docs/local_site/static/fonts/HKGrotesk/ (stored 0%)
updating: gx/uncommitted/data_docs/local_site/static/fonts/HKGrotesk/HKGrotesk-SemiBold.otf (deflated 37%)
updating: gx/uncommitted/data_docs/local_site/static/fonts/HKGrotesk/HKGrotesk-Italic.otf (deflated 35%)
updating: gx/uncommitted/data_docs/local_site/static/fonts/HKGrotesk/HKGrotesk-Regular.otf (deflated 36%)
updating: gx/uncommitted/data_docs/local_site/static/fonts/HKGrotesk/HKGrotesk-LightItalic.otf (deflated 36%)
updating: gx/uncommitted/data_docs/local_site/static/fonts/HKGrotesk/HKGrotesk-Medium.otf (deflated 36%)
updating: gx/uncommitted/data_docs/local_site/static/fonts/HKGrotesk/HKGrotesk-MediumItalic.otf (deflated 35%)
updating: gx/uncommitted/data_docs/local_site/static/fonts/HKGrotesk/HKGrotesk-Light.otf (deflated 37%)
updating: gx/uncommitted/data_docs/local_site/static/fonts/HKGrotesk/HKGrotesk-Bold.otf (deflated 38%)
updating: gx/uncommitted/data_docs/local_site/static/fonts/HKGrotesk/HKGrotesk-BoldItalic.otf (deflated 36%)
updating: gx/uncommitted/data_docs/local_site/static/fonts/HKGrotesk/HKGrotesk-SemiBoldItalic.otf (deflated 36%)
updating: gx/uncommitted/data_docs/local_site/static/styles/ (stored 0%)
updating: gx/uncommitted/data_docs/local_site/static/styles/data_docs_custom_styles_template.css (deflated 74%)
updating: gx/uncommitted/data_docs/local_site/static/styles/data_docs_default_styles.css (deflated 64%)
updating: gx/uncommitted/data_docs/local_site/validations/aircraft_suite/__none__/20260218T151359.547244Z/ (stored 0%)
updating: gx/uncommitted/data_docs/local_site/validations/aircraft_suite/__none__/20260218T151359.547244Z/pandas_datasource-aircraft_data.html (deflated 81%)
  adding: gx/uncommitted/data_docs/local_site/validations/aircraft_suite/__none__/20260218T152931.231161Z/ (stored 0%)
  adding: gx/uncommitted/data_docs/local_site/validations/aircraft_suite/__none__/20260218T152931.231161Z/pandas_datasource-aircraft_data.html (deflated 83%)

In [ ]:
from google.colab import files
files.download("aircraft_validation_report.zip")

# Machine Learning

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import shap
import matplotlib.pyplot as plt
from fairlearn.metrics import MetricFrame, selection_rate, false_positive_rate, false_negative_rate
from IPython.display import IFrame

In [ ]:
df = pd.read_csv("aircraft_sensor_data.csv")  # Replace with your file path

#  Add synthetic sensitive attribute if missing

if "machine_type" not in df.columns:
    df["machine_type"] = np.random.choice(["A", "B"], size=df.shape[0])

print("Dataset preview:")
display(df.head())
print("\nColumns:", df.columns)

In [ ]:
features = ["rpm", "vibration_rms", "temperature", "acoustic_db", "machine_type"]
target = "risk"

X = df[features]
y = df[target]

X = pd.get_dummies(X, columns=["machine_type"], drop_first=True)  # creates machine_type_B

# Train-test split (80-20)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [ ]:
# 8️⃣ Random Forest Training
# =========================
rf = RandomForestClassifier(n_estimators=150, random_state=42)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

In [ ]:
print("\n=== Random Forest Evaluation ===")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

In [ ]:
# 🔟 Feature Importance (creative visualization)
# =========================
importances = rf.feature_importances_
feat_names = X_train.columns

plt.figure(figsize=(8,5))
bars = plt.barh(feat_names, importances, color=plt.cm.viridis(importances))
plt.title("🎯 Random Forest Feature Importance", fontsize=16)
plt.xlabel("Importance", fontsize=12)
plt.ylabel("Features", fontsize=12)

# Add value labels
for bar in bars:
    width = bar.get_width()
    plt.text(width + 0.005, bar.get_y() + bar.get_height()/2, f"{width:.2f}", va='center')
plt.show()

In [ ]:
# 1️⃣1️⃣ SHAP Explanations
# =========================
explainer = shap.TreeExplainer(rf)
shap_values = explainer(X_test)

# Summary plot (beeswarm)
shap.summary_plot(shap_values, X_test, plot_type="dot", show=True)

# Summary bar plot
shap.summary_plot(shap_values, X_test, plot_type="bar", show=True)

In [ ]:
# 1️⃣2️⃣ Bias / Fairness Analysis
# =========================
sensitive_feature = X_test["machine_type_B"]

metrics = {
    "accuracy": lambda y_true, y_pred: (y_true == y_pred).mean(),
    "selection_rate": selection_rate,
    "false_positive_rate": false_positive_rate,
    "false_negative_rate": false_negative_rate
}

mf = MetricFrame(metrics=metrics,
                 y_true=y_test,
                 y_pred=y_pred,
                 sensitive_features=sensitive_feature)

print("\n=== Bias / Fairness Analysis by Machine Type ===")
display(mf.by_group)